---
apiVersion: cert-manager.k8s.cloudflare.com/v1
kind: OriginIssuer
metadata:
  name: cloudflare-prod-issuer
  namespace: bitwarden
spec:
  requestType: OriginECC
  auth:
    serviceKeyRef:
      name: cloudflare-service-key
      key: key