---
- name: Check if k3s exists
  stat:
    path: /usr/local/bin/k3s
  register: k3s_stat_result

- name: Check k3s version
  shell: k3s --version
  when: k3s_stat_result.stat.exists
  register: k3s_version_result

- set_fact:
    install_k3s: "{% if k3s_stat_result.stat.exists and k3s_version in k3s_version_result.stdout %}false{% else %}true{% endif %}"


- name: Delete k3s if already present
  file:
    path: /usr/local/bin/k3s
    state: absent
  when: install_k3s

- name: Download k3s binary x64
  get_url:
    url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  when:
    - install_k3s
    - ansible_facts.architecture == "x86_64"

- name: Download k3s binary arm64
  get_url:
    url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s-arm64
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  when:
    - install_k3s
    - ( ansible_facts.architecture is search("arm") and
        ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: Download k3s binary armhf
  get_url:
    url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s-armhf
    dest: /usr/local/bin/k3s
    owner: root
    group: root
    mode: 0755
  when:
    - install_k3s
    - ansible_facts.architecture is search("arm")
    - ansible_facts.userspace_bits == "32"