---
- name: Create ingress namespace
  k8s:
    state: present
    definition: "{{ lookup('file', 'ingress/ns.yml') }}"
    kubeconfig: "{{ kubeconfig }}"

- name: Move ingress to its own namespace
  lineinfile:
    path: /var/lib/rancher/k3s/server/manifests/traefik.yaml
    insertafter: '^spec:$'
    line: "  targetNamespace: ingress"
    firstmatch: yes

- name: Try to delete ingress in kube-system namespace
  shell: helm --kubeconfig {{ kubeconfig }} -n kube-system delete traefik
  register: traefik_delete
  failed_when: false
  changed_when: "'uninstalled' in traefik_delete.stdout"