---
- name: Delete linkerd if already present
  file:
    path: /usr/local/bin/linkerd
    state: absent

- name: Download linkerd binary x64
  get_url:
    url: https://github.com/linkerd/linkerd2/releases/download/{{ linkerd_version }}/linkerd2-cli-{{ linkerd_version }}-linux-amd64
    dest: /usr/local/bin/linkerd
    owner: root
    group: root
    mode: 0755
  when: ansible_facts.architecture == "x86_64"

- name: Download linkerd binary arm64
  get_url:
    url: https://github.com/linkerd/linkerd2/releases/download/{{ linkerd_version }}/linkerd2-cli-{{ linkerd_version }}-linux-arm64
    dest: /usr/local/bin/linkerd
    owner: root
    group: root
    mode: 0755
  when:
    - ( ansible_facts.architecture is search("arm") and
        ansible_facts.userspace_bits == "64" ) or
      ansible_facts.architecture is search("aarch64")

- name: Download linkerd binary arm
  get_url:
    url: https://github.com/linkerd/linkerd2/releases/download/{{ linkerd_version }}/linkerd2-cli-{{ linkerd_version }}-linux-arm
    dest: /usr/local/bin/linkerd
    owner: root
    group: root
    mode: 0755
  when:
    - ansible_facts.architecture is search("arm")
    - ansible_facts.userspace_bits == "32"

- name: Get linkerd manifest
  shell: linkerd install --kubeconfig {{ kubeconfig }} --ignore-cluster
  changed_when: false
  register: linkerd_install

- name: Install linkerd
  k8s:
    state: present
    definition: "{{ linkerd_install.stdout }}"
    kubeconfig: "{{ kubeconfig }}"

- name: Wait for linkerd to be ready
  command: linkerd check --kubeconfig {{ kubeconfig }}
  changed_when: false