---
- name: Install python deps
  apt:
    name:
      - python3-pip
      - python3-setuptools
      - python3-dev

- name: Install k8s module deps
  pip:
    name:
      - openshift

- include: cert-manager.yml

- include: cloudflare-issuer.yml

- include: linkerd.yml

- include: nfs-provisioner.yml

- include: ingress.yml

- include: ddclient.yml

- include: prometheus-operator.yml

- include: bitwarden.yml