---
- name: Install python deps
  apt:
    name:
      - python-pip
      - python-setuptools
      - python-dev

- name: Install k8s module deps
  pip:
    name:
      - openshift

- include: linkerd.yml

- include: nfs-provisioner.yml

- include: ingress.yml

- include: ddclient.yml

- include: cert-manager.yml
